name: CI-DockerBuild

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    # El tipo de máquina virtual donde se ejecutará el job
    runs-on: ubuntu-latest

    # Los pasos que componen el job
    steps:
    # 1. Clona tu repositorio en la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4
